name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # This runs at exactly 5:00 AM UTC every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: my-submissions
          verbose: true
