name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run LeetCode Sync
        run: npx -y github:qinghaoh/leetcode-sync --dir my-submissions
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
